"""
Django settings for perfil project.

Generated by 'django-admin startproject' using Django 4.2.

For more information on this file, see
https://docs.djangoproject.com/en/4.2/topics/settings/

For the full list of settings and their values, see
https://docs.djangoproject.com/en/4.2/ref/settings/
"""

from pathlib import Path
import os

# Build paths inside the project like this: BASE_DIR / 'subdir'.
#BASE_DIR = Path(__file__).resolve().parent.parent
BASE_DIR = os.path.dirname(os.path.dirname(os.path.abspath(__file__)))

# Quick-start development settings - unsuitable for production
# See https://docs.djangoproject.com/en/4.2/howto/deployment/checklist/

# SECURITY WARNING: keep the secret key used in production secret!
SECRET_KEY = 'django-insecure-=$8!^#l+kmv&jd(26yk16ixn8!s7pd6gg^yf_i4mw+@2$6a=nm'

# SECURITY WARNING: don't run with debug turned on in production!
#DEBUG = True
#ALLOWED_HOSTS = ['*'] 127.0.0.1

DEBUG = True
#ALLOWED_HOSTS = ['127.0.0.1', '.pythonanywhere.com']
ALLOWED_HOSTS = ['*']

# Application definition

INSTALLED_APPS = [
       
   #usar o login padrão - Exigido como primeiro app da lista 
    'accounts.apps.AccountsConfig',
    'django.contrib.admin',
    'django.contrib.auth',
    'django.contrib.contenttypes',
    'django.contrib.sessions',
    'django.contrib.messages',
    'django.contrib.staticfiles',
    'django_cleanup.apps.CleanupConfig',
    'django_user_agents',
    'bootstrap4', 
    
   #######################################################
    #Ativa os módulos dos apps (arquivo apps.py de cada um)
    ##################################################
    'quizes.apps.QuizesConfig',
    'questions.apps.QuestionsConfig',
    'result.apps.ResultConfig',
    'personality.apps.PersonalityConfig',
    'preference.apps.PreferenceConfig',
]

MIDDLEWARE = [
    'django.middleware.security.SecurityMiddleware',
    'django.contrib.sessions.middleware.SessionMiddleware',
    'django.middleware.common.CommonMiddleware',
    'django.middleware.csrf.CsrfViewMiddleware',
    'django.contrib.auth.middleware.AuthenticationMiddleware',
    'django.contrib.messages.middleware.MessageMiddleware',
    'django.middleware.clickjacking.XFrameOptionsMiddleware',
    # Definirá um is_ajax método em cada solicitação antes de ser recebido pela exibição.
    'quizes.middlewares.AjaxMiddleware', 
]

ROOT_URLCONF = 'perfil.urls'

TEMPLATES = [
    {
        'BACKEND': 'django.template.backends.django.DjangoTemplates',
        'DIRS': ['templates'],
        'APP_DIRS': True,
        'OPTIONS': {
            'context_processors': [
                'django.template.context_processors.debug',
                'django.template.context_processors.request',
                'django.contrib.auth.context_processors.auth',
                'django.contrib.messages.context_processors.messages',
                ### Validador automatico do app Preference
                'preference.validaPreferencias.verificar_preferencias', 
            ],
        },
    },
]

WSGI_APPLICATION = 'perfil.wsgi.application'


# Database
# https://docs.djangoproject.com/en/4.2/ref/settings/#databases

DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.sqlite3',
        'NAME': 'quizes.sqlite3',
    }
}


''' ######## POSTGRESQL13
DATABASES = {
    'default': {
        'ENGINE': 'django.db.backends.postgresql',
        'NAME': 'disc',
        'USER': 'cazuza',
        'PASSWORD': '17032023',
        'HOST': 'localhost',
        'PORT': '5432',
        #'ENGINE': 'django.db.backends.sqlite3',
        #'NAME': 'db.sqlite3',
    }
}

'''
# Banco de dados GeoLite2-City.mmdb para geolocalização
GEOIP_PATH = os.path.join(BASE_DIR, 'dados\GeoLite2-City.mmdb') # D:\perfil\dados


# Password validation
# https://docs.djangoproject.com/en/4.2/ref/settings/#auth-password-validators

AUTH_PASSWORD_VALIDATORS = [
    {
        'NAME': 'django.contrib.auth.password_validation.UserAttributeSimilarityValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.MinimumLengthValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.CommonPasswordValidator',
    },
    {
        'NAME': 'django.contrib.auth.password_validation.NumericPasswordValidator',
    },
]


# Internationalization
# https://docs.djangoproject.com/en/4.2/topics/i18n/

LANGUAGE_CODE = 'pt-br'
TIME_ZONE = 'America/Sao_Paulo'
USE_I18N = True
USE_TZ = True


# Static files (CSS, JavaScript, Images)
# https://docs.djangoproject.com/en/4.2/howto/static-files/

STATIC_URL = '/static/'
MEDIA_URL = '/media/'
STATIC_ROOT = os.path.join(BASE_DIR, 'staticfiles')
MEDIA_ROOT = os.path.join(BASE_DIR, 'media')


#Sistema de autenticação personalizado
#AUTH_USER_MODEL = 'usuarios.CustomUsuario'

#Enviar email com token via terminal
EMAIL_BACKEND = 'django.core.mail.backends.console.EmailBackend'

'''
EMAIL_HOST = 'localhost'
EMAIL_HOST_USER = 'no-reply@quizcenter.com.br'
EMAIL_USER_TSL = True
EMAIL_HOST_PASSWORD = 'minhasenha'
'''

### Configurações de autenticação - São três constantes exigidas
LOGIN_URL = 'login'
LOGIN_REDIRECT_URL = 'quizes:index'
LOGOUT_REDIRECT_URL = 'quizes:index'


# Default primary key field type
# https://docs.djangoproject.com/en/4.2/ref/settings/#default-auto-field
DEFAULT_AUTO_FIELD = 'django.db.models.BigAutoField'

