# Generated by Django 4.2 on 2024-04-20 20:33

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookies',
            name='durationCookie',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 27, 20, 33, 54, 872918, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
