# Generated by Django 4.2 on 2024-04-21 03:44

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0002_alter_cookies_durationcookie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookies',
            name='durationCookie',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 3, 44, 7, 749774, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='SO',
            field=models.CharField(default='', max_length=50),
        ),
        migrations.AlterField(
            model_name='preference',
            name='ipTerminal',
            field=models.CharField(default=None, max_length=30),
        ),
    ]
