# Generated by Django 4.2 on 2024-04-21 03:56

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0003_alter_cookies_durationcookie_alter_preference_so_and_more'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookies',
            name='durationCookie',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 3, 56, 49, 862824, tzinfo=datetime.timezone.utc), null=True),
        ),
        migrations.AlterField(
            model_name='preference',
            name='cidade',
            field=models.CharField(default=None, max_length=70),
        ),
        migrations.AlterField(
            model_name='preference',
            name='pais',
            field=models.CharField(default=None, max_length=70),
        ),
    ]
