# Generated by Django 4.2 on 2023-08-06 15:23

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0003_alter_cookies_durationcookie'),
    ]

    operations = [
        migrations.AlterField(
            model_name='cookies',
            name='durationCookie',
            field=models.DateTimeField(default=datetime.datetime(2023, 8, 13, 15, 23, 32, 545896, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
