# Generated by Django 4.2 on 2024-04-21 03:59

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('preference', '0004_alter_cookies_durationcookie_alter_preference_cidade_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='preference',
            name='cidade',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='ipTerminal',
        ),
        migrations.RemoveField(
            model_name='preference',
            name='pais',
        ),
        migrations.AlterField(
            model_name='cookies',
            name='durationCookie',
            field=models.DateTimeField(default=datetime.datetime(2024, 4, 28, 3, 59, 56, 987053, tzinfo=datetime.timezone.utc), null=True),
        ),
    ]
