# Generated by Django 4.2 on 2023-08-10 02:59

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Quiz',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100, verbose_name='Nome geral:')),
                ('topic', models.CharField(max_length=100, verbose_name='Tema específico:')),
                ('created', models.DateTimeField(auto_now_add=True, verbose_name='Criado em:')),
                ('number_of_questions', models.IntegerField(help_text='Número de questões', verbose_name='Questões:')),
                ('time', models.IntegerField(help_text='Tempo máximo em minutos', verbose_name='Tempo:')),
                ('required_score_to_pass', models.IntegerField(help_text='Pontuação exigida para aprovação em %', verbose_name='Pontuação')),
                ('difficulty', models.CharField(choices=[('Fácil', 'Fácil'), ('Médio', 'Médio'), ('Avançado', 'Avançado')], max_length=10, verbose_name='Nível:')),
                ('user', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'verbose_name_plural': 'Questionários',
            },
        ),
    ]
